### PR TITLE
Esm

### PR DESCRIPTION
**Pull request by brettz9**
Builds on the docs PR (#1).

Although one technically can, and some do, release distribution files which do not have the external modules bundled into them, I think this is like offering pre-built binaries which still require a compilation step.

For those who want to consume the library as part of a bundling chain, your `package.json` `module` property can point them to the source, so they can do their own bundling if they wish (and get the advantage of being able to compile against the latest version of the external dependencies if the requiring library hasn't updated its bundled copies).

But in my strong opinion, dist files ought to bundle in the external dependencies (as in this PR) so that projects can work out of the box without a build step in browser applications using them. While some might argue that bundlers will be necessary anyways, I very much disagree in that it is easier to debug without the slowed feedback cycle of an extra build step.

And even the ugliness of needing to include the `./node_modules/...` paths may be removed in the future as browsers implement "import maps" which browsers have already begun to support, allowing one to specify how module specifiers such as "kld-affine" should map to URL paths that the browser can understand.

Although this PR adds the node-resolve plugin (since Rollup, being agnostic to Node, otherwise doesn't understand to look in `node_modules`), it does not need the commonjs plugin, since your dependencies, kld-affine and kld-polynomial are now expressed as modules and designated in `package.json` through the `module` property.

### CODE REVIEW

**Comment by thelonious** [comment]
Admittedly, some of the subtleties on dist files are lost on me at this time. My use case for this libs has been for command-line nodejs work, which is too narrow. As I start taking advantage of the dist system you have built, I'm likely to form opinions at that time. I'll bookmark this PR for later consideration :)

**Comment by brettz9** [comment]
Basically, it boils down to the fact that I'd like for my browser applications to be able to do the following, and not need any build steps--just use the ESM support now built into a modern browser like Firefox or Chrome:

```js
import {Rectangle2D} from '../node_modules/kld-contours/dist/index-esm.js';
```

If there are still imports within `index-esm.js` that are like this:

```js
import {Point2D} from "kld-affine";
```

...then I can't import your file without a build step as browsers don't know how to find `kld-affine`--they have no mechanism to designate, like Node, that they should look within `node_modules`, etc.

As far as other uses of your work, you might consider what applications they may have in integrating into the likes of our https://github.com/SVG-Edit/svgedit project. (I'm only the reluctant lead atm because the real developers have moved on, but I got involved by ESM-modularizing and linting it, etc., besides for some current needs of mine, in the hopes that others might be inspired to advance it with some of the grunt work out of the way.) This is a project which Wikipedia still has it in mind to integrate: https://phabricator.wikimedia.org/T40271 , which would I think be a really exciting development for the web.

**Comment by brettz9** [comment]
Btw, just a friendly reminder so you don't accidentally develop on the wrong branch, `development` is currently behind `master` on `kld-contours`.

**Comment by thelonious** [comment]
/face-palm I guess I'm jumping around between too many repos and missed that. That's fixed now. Thanks for letting me know.

Yeah, I remember SVGEdit. Impressive amount of work there.

Thanks for the clarification on the ESM support. From what you've described, I'm in agreement. It seems counter-productive to require people to bundle if all they what to do is test some things in your code.

**Comment by brettz9** [comment]
Yeah. One does have to watch though for `node_modules` which can, e.g., when there are different versions of dependencies, appear in different locations. Older versions of Node were also not flattened as they are now.

**Pull request merged**
