### PR TITLE
- Fix JSDoc references (though did not fix external module references)

### PR DESCRIPTION
**Pull request by brettz9**
Besides the fixes in this PR, one is technically supposed to use the `@external` tag to define objects from outside of the library (e.g., kld-affine) and reference it the form `external:`, e.g., `@param {external:kld-affine-Point2D}` (not sure if hyphens are restricted; if you decide to do it, you can check that the docs actually come through).

Since it makes no practical difference as far as giving you better linking, and in case you ever wanted to put these repos together in a monorepo, I didn't add this `@external` change in this PR (I did a little already in the code currently in kld-intersections though--see its index.js to see if you want to follow that style).

### CODE REVIEW

**Comment by thelonious** [comment]
Thanks for these fixes. At least I was wrong consistently.

Yeah, I'll have to dig deeper in to JSDoc (wish the site with the spec were up!). It's truly good to have some docs, but I'm not super happy with the navigation (Modules, Namespaces, and Classes have the same lists, I can't see all properties and methods of a class in a list, etc.). Hopefully these things can be resolved as I learn more.

**Comment by brettz9** [comment]
Yeah, hope they get the site back online soon.

If you have time to invest in learning it all, Typescript seems quite actively maintained and supported, and it seems to me there are some good signs of jsdoc and Typescript continuing to harmonize with each other. I'm not a fan of changing JavaScript to non-standard syntax, but one may be able to get away with using only the comments or external type files to get docs (though Typescript flavor for modules). But if you go that route, hopefully this will at least have been useful, as Typescript does rely on jsdoc.

As far as jsdoc's module syntax, I'm not really even sure what it means to be a inner, static, or instance member of a module, since a module is not a JavaScript construct. Just thought that it was better to get the links going, but of course, feel free to represent things differently as you like.

**Comment by thelonious** [comment]
I'm mixed on TS atm. Ironcially, it's very similar to what I wanted JS to be about 10 years ago. I don't think one would go wrong using it, but "always bet on JS".

**Comment by brettz9** [comment]
Yeah... Coffeescript has diminished, esp. as ES6 has incorporated some of its advantages, and I have a feeling we may see the same with Typescript. And folks really needing static typing can use WebAssembly, getting its performance benefits as well.

**Pull request merged**
